/* world.hpp — one episode: one brain on one patch of ground, under one weather,
 * walking one mission. Port of world.js.
 *
 * Fairness rule, and it is the thing that makes selection mean anything: every
 * walker spawns at the SAME spot in the SAME pose on the SAME terrain, gets the
 * SAME waypoints, the SAME gusts, the SAME shoves at the SAME instants, and even
 * the SAME stream of sensor noise. The only difference between two of them is the
 * weights in their heads.
 *
 * ONE WALKER PER WORLD, where the JS carries a list. This is exactly equivalent
 * and not an approximation: walkers never interact, never collide and never see
 * each other, and the shared waypoint chain is generated by its own RNG in leg
 * order, so a lone walker draws the identical points at the identical times. The
 * JS already runs this way in practice — the trainer dispatches one brain per job.
 * What it buys here is that no thread ever touches another thread's episode.
 *
 * Every episode replays the curriculum in order:
 *   0.0 - 1.6 s   STAND     rise out of the half-squat and reach full height
 *   1.6 - 3.2 s   BALANCE   hold it; from stage 2 on, take a shove
 *   3.2 s - end   WALK      chase waypoints
 * The first two windows are short on purpose. They were 2.5 s each until a trace
 * showed 0 of 40 first-generation walkers still upright at 5.0 s — so not one of
 * them ever entered the walk phase, and the walking half of the fitness function
 * was unreachable dead code.
 */
#pragma once
#include <vector>
#include <string>
#include <cmath>
#include <limits>
#include "walker.hpp"

constexpr double PHASE_STAND = 1.6;
constexpr double PHASE_BALANCE = 3.2;
constexpr double ARRIVE_RADIUS = 0.55;
constexpr double START_BUDGET = 17;        // s on each walker's own clock
/* Reaching a waypoint has to buy enough clock to actually attempt the next one.
 * At 9 s it did not: a walker covers ~1.3-2.3 m per leg at roughly 0.2 m/s of
 * honest closure, so nine seconds bought under half a leg and the second waypoint
 * was unreachable even in principle. Arriving must compound. */
constexpr double ARRIVAL_TIME = 50;
constexpr double MAX_CLOCK = 90;
constexpr double RISE_GRACE = 5.0;         // s of extra clock and phase delay for a floor start
constexpr double EPISODE_HARD_CAP = 130;   // s of sim, last-resort backstop
constexpr int MAX_ARRIVALS = 40;

enum class Phase { STAND, BALANCE, WALK };

/* What the environment throws at the population at each stage.
 *
 * TERRAIN AND FLOOR STARTS BEGIN AT STAGE 1. The old table saved them for later
 * and the arithmetic of "later" was fatal: effective difficulty is stage.terrain
 * MULTIPLIED by the curriculum ramp, so a fleet parked on stage 2 trained at
 * 0.12 x 0.15 = 0.018 — 1.8 cm bumps — while the first stair riser sat 1.8 m from
 * the spawn and the fleet's mean walked distance was 0.65 m. Terrain competence
 * was not being under-trained, it was untrained.
 *
 * What made front-loading unsafe before was that terrain arrived as a step change
 * for the whole fleet at once. That is fixed differently now: every episode draws
 * its own difficulty from a spread, so one generation contains easy and hard
 * ground simultaneously and selection has a gradient at every roughness at once.
 *
 * WHAT IS STILL TAPERED, and why it is not the same thing. Terrain, floor starts
 * and crouch depth are SKILLS — the walker can get better at them, so meeting them
 * early is practice. Wind and shoves are DISTURBANCES: they add variance to the
 * measurement without teaching anything, so front-loading them makes selection
 * noisier about who is actually better. */
struct Stage { int n; const char* name; double pushes, wind, terrain, turn, spin, ground, crouchDepth, seat, seatDepth, pose; };
inline const std::vector<Stage>& STAGES() {
    static const std::vector<Stage> s = {
        { 1, "stand",   0.00, 0.00, 0.35, 0.15, 0.00, 0.45, 0.35, 0.35, 0.15, 0.40 },
        { 2, "balance", 0.20, 0.00, 0.55, 0.30, 0.18, 0.45, 0.45, 0.35, 0.30, 0.40 },
        // Stage 3 is purely "learn to turn". It used to raise four demands at once
        // — shoves x2, turn x3.3, crouch depth x1.7, turn-arounds x1.55 — and a
        // fleet worth 21,572 on stage 2 scored 3,605 on arrival, twice.
        { 3, "turn",    0.35, 0.00, 0.75, 0.70, 0.30, 0.45, 0.55, 0.40, 0.50, 0.40 },
        // Stage 4 is where the disturbances start to bite, one notch at a time.
        { 4, "terrain", 0.50, 0.35, 0.90, 1.00, 0.33, 0.45, 0.75, 0.40, 0.75, 0.40 },
        // Stage 5 consolidates: full shoves, full wind, the deepest starts.
        { 5, "wind",    1.00, 1.00, 1.00, 1.00, 0.33, 0.45, 1.00, 0.30, 1.00, 0.40 }
    };
    return s;
}

/* NaN means "not supplied", so an explicit 0 is honoured. exam.js passes
 * groundFrac: 0, and a plain sentinel of -1 or 0 would silently turn that into
 * "use the stage default" — the exam would stop being the exam. */
constexpr double UNSET = std::numeric_limits<double>::quiet_NaN();
inline bool isSet(double v) { return !std::isnan(v); }
inline double pick(double v, double dflt) { return isSet(v) ? v : dflt; }

struct WorldOpts {
    int stage = 1;
    double terrainDifficulty = UNSET;
    std::string terrainId = "rolling";
    int missionSeed = 1;
    uint32_t noiseSeed = 20260729;
    bool noise = true;
    int episodeSlot = 0, episodeCount = 0;
    double groundFrac = UNSET, crouchDepth = UNSET, seatFrac = UNSET, seatDepth = UNSET;
    double poseFrac = UNSET;
    double windScale = UNSET, pushScale = UNSET;
    bool terrainFixed = false;
    double startBudget = 0;                 // 0 = fall back to START_BUDGET, like `||`
};

struct Point { double x, z, y; };

class World {
public:
    const Model* model = nullptr;
    Stage stage{};
    Rng rng, pointRng;
    double time = 0;
    long long tick = 0;
    Phase phase = Phase::STAND;
    bool noise = true;
    double arriveRadius = ARRIVE_RADIUS, arrivalTime = ARRIVAL_TIME;

    double frictionScale = 1, torqueScale = 1, gainScale = 1;
    std::vector<double> jitterPose;
    Terrain terrain;

    double windFrac = 0, windSpeed = 0, windDir = 0, windTarget = 0;
    bool windOn = false;
    double wind[3] = {0,0,0};

    double pushLevel = 0, nextPush = std::numeric_limits<double>::infinity();

    double startYaw = 0;
    Point spawn { 0, 0, 0 };
    std::vector<Point> points;
    double lastHeading = 0;

    bool hasStartPose = false;
    Pose startPose;
    double riseGrace = 0, phaseStand = PHASE_STAND, phaseBalance = PHASE_BALANCE;

    Walker walker;

    /* Default-constructible so a worker thread can hold ONE World and re-init it
     * per episode. Every member container is refilled with assign()/clear(), which
     * keeps capacity, so after the first episode a thread allocates nothing at all
     * — and a trainer runs a few thousand episodes per generation. */
    World() = default;
    World(const Model& m, Net* brain, const WorldOpts& o) { init(m, brain, o); }

    void init(const Model& M, Net* brain, const WorldOpts& o) {
        model = &M;
        const auto& ST = STAGES();
        stage = ST[(size_t)std::max(0, std::min((int)ST.size() - 1, o.stage - 1))];
        rng.reseed((uint32_t)(4100 + (uint32_t)o.missionSeed * 7919u));
        noise = o.noise;

        // ---- per-episode domain randomisation, drawn once and shared ----
        Rng& r = rng;
        frictionScale = 1 + (r() - 0.5) * 0.30;
        torqueScale   = 1 + (r() - 0.5) * 0.16;
        gainScale     = 1 + (r() - 0.5) * 0.20;
        if (!noise) { frictionScale = 1; torqueScale = 1; gainScale = 1; }
        // One jitter draw for the whole fleet: every walker starts in the same
        // imperfect pose, so a lucky spawn cannot be mistaken for a good brain.
        jitterPose.assign(M.nj, 0.0);
        if (noise) for (int j = 0; j < M.nj; j++) jitterPose[j] = (r()*2 - 1) * 0.025;

        /* ---- terrain ----
         * Difficulty is drawn PER EPISODE from a spread below the stage ceiling,
         * and the bank is STRATIFIED rather than i.i.d. With seven episodes the
         * REALISED mix of a generation — how many staircases, how rough, how many
         * floor starts — is itself a random variable and it swings hard: one
         * unchanged brain scores 7,786 on generation 90's bank and 416 on
         * generation 100's, an 18.7x swing with not one weight altered, and it
         * reproduces the live run's "best fitness" curve to the digit. A curve
         * like that is a picture of the calendar.
         *
         * So the COMPOSITION is fixed and only the INSTANCES vary: episode slot e
         * owns band e of the difficulty range and surface e % 3, and floor starts
         * are dealt out evenly across the slots. */
        const int E = o.episodeCount, eSlot = o.episodeSlot;
        const bool strat = E > 1 && eSlot >= 0 && eSlot < E;
        /* Bresenham: exactly floor(n*frac) of the n slots, spread evenly rather
         * than bunched at one end — a block of floor starts at the easy end of the
         * difficulty ladder would just be a different bias. */
        auto quota = [](int i, int n, double frac) {
            return std::floor((i + 1) * frac) > std::floor(i * frac);
        };

        const double terrCeil = pick(o.terrainDifficulty, 1.0) * stage.terrain;
        double terrFrac;
        if (o.terrainFixed) terrFrac = 1;
        else if (strat) terrFrac = (eSlot + r()) / E;   // this slot owns one band, jittered inside it
        else terrFrac = r();
        const double terrDiff = o.terrainFixed ? terrCeil : terrCeil * (0.2 + 0.8 * terrFrac);
        /* "varied" is not a surface — it means draw one per episode, so the fleet
         * meets undulation, staircases and both together instead of specialising
         * on whichever single one the run was launched with. */
        std::string tid = o.terrainId.empty() ? std::string("rolling") : o.terrainId;
        if (tid == "varied") {
            static const char* opts3[3] = { "rolling", "stairs", "mixed" };
            const int k = strat ? (eSlot % 3) : ((int)std::floor(r() * 3) % 3);
            tid = opts3[k];
        }
        if (terrCeil <= 0) tid = "flat";
        TerrainId tenum = TerrainId::FLAT;
        if (tid == "rolling") tenum = TerrainId::ROLLING;
        else if (tid == "stairs") tenum = TerrainId::STAIRS;
        else if (tid == "mixed") tenum = TerrainId::MIXED;
        terrain = Terrain(tenum, terrDiff, r);

        // ---- weather ----
        windFrac = stage.wind * pick(o.windScale, 1.0);
        windOn = windFrac > 0.001;
        windSpeed = 0;
        windDir = r() * 3.141592653589793 * 2;
        windTarget = windFrac * (4 + r() * 6);          // m/s
        wind[0] = wind[1] = wind[2] = 0;

        // ---- shoves ----
        pushLevel = stage.pushes * pick(o.pushScale, 1.0);

        /* ---- the shared mission ----
         * Stratified too, and not a small term. The waypoint chain is laid out
         * relative to the start heading, so yaw does not change where the walker
         * is asked to go — but the terrain is a fixed field in world coordinates,
         * so yaw decides whether the route crosses the ridges or runs along them.
         * The slot ordering is deliberately NOT the terrain's: keyed to eSlot
         * directly, the gentlest ground would always be paired with the same
         * heading and the bank would trade one bias for another, so a stride
         * coprime with the episode count permutes the bands instead. */
        double yawFrac;
        if (strat) {
            int k = 2;
            auto gcd = [](int a, int b) { while (b) { int t = a % b; a = b; b = t; } return a; };
            while (k < E && gcd(k, E) != 1) k++;
            yawFrac = (double)(((eSlot * k) % E) + r()) / E;
        } else yawFrac = r();
        startYaw = (yawFrac * 2 - 1) * 3.141592653589793;
        spawn = { 0, 0, 0 };
        points.clear();
        pointRng.reseed((uint32_t)(6700 + (uint32_t)o.missionSeed * 3571u));
        lastHeading = startYaw;
        spawnPoint();

        /* ---- where everyone starts ----
         * One draw for the whole fleet, like the pose jitter and the weather. */
        const double gFrac = pick(o.groundFrac, stage.ground);
        const double maxDepth = pick(o.crouchDepth, stage.crouchDepth);
        const double seatFrac = pick(o.seatFrac, stage.seat);
        hasStartPose = false;
        const bool groundHit = strat ? quota(eSlot, E, gFrac) : false;
        const bool seatHit = strat ? (groundHit && quota(eSlot, E, gFrac * seatFrac)) : false;
        /* Seated only, and ramped rather than jumped. The side-lying pose is not
         * recoverable by ANY command sequence — it needs a roll-over first — and
         * spending the floor budget on a rung nothing can climb just deletes
         * episodes that could have taught the rung that IS climbable. The full
         * seat used to be handed over whole, and the exam read 0/6 on it for every
         * champion this project has produced while the folded squat one rung below
         * read 3/6; seatAt() interpolates between them. Drawn across a band rather
         * than always the deepest, because the shallow rungs are banked skill and
         * a fleet that only ever sees the hardest one trades them away. */
        if (gFrac > 0 && seatFrac > 0 && !M.groundPoses.empty() &&
            (strat ? seatHit : (rng() < gFrac * seatFrac))) {
            const double maxSeat = pick(o.seatDepth, stage.seatDepth);
            startPose = M.seatAt(maxSeat * (0.25 + 0.75 * rng()));
            hasStartPose = true;
        }
        /* ---- the pose pool ----
         * A slice of the ground budget spent on one of M.startPoses instead of a
         * rung on the crouch/seat ramp. The ramp varies one thing — how far down
         * the walker starts — and every rung on it is square to the world,
         * symmetric and standing on its feet. The pool is the other axis: on the
         * hands, on one arm, on the knees, rolled onto an edge, folded to one side.
         *
         * Placed AFTER the seat test and BEFORE the crouch test, consuming exactly
         * one draw when it fires. That position is part of the interface, not an
         * implementation detail: `verify --episode` compares this RNG stream draw
         * for draw against a recorded JS episode, so moving the call moves every
         * later draw and the whole environment diverges. */
        /* `pose` is a share of ALL episodes, not of the ground episodes. Nested
         * inside groundFrac, `ground 0.45, pose 0.30` gave the fourteen floor
         * poses 13.5% of spawns rather than the 30% the table appeared to say.
         * 0.40 now means four episodes in ten start in a pose. */
        const double poseFrac = pick(o.poseFrac, stage.pose);
        const bool poseHit = strat ? quota(eSlot, E, poseFrac) : false;
        if (!hasStartPose && poseFrac > 0 && !M.startPoses.empty() &&
            (strat ? poseHit : (rng() < poseFrac))) {
            const int n = (int)M.startPoses.size();
            startPose = M.startPoses[std::min(n - 1, (int)(rng() * n))];
            hasStartPose = true;
        }
        if (!hasStartPose && gFrac > 0 && maxDepth > 0 && (strat ? groundHit : (rng() < gFrac))) {
            // draw a depth rather than always the deepest: the fleet needs to keep
            // the shallow rise it has banked, not trade it for the deep one
            startPose = M.crouchAt(0.25 * maxDepth + 0.75 * maxDepth * rng());
            hasStartPose = true;
        }
        // Rising takes time an ordinary crouch does not need, so the phase
        // boundaries and the clock both slide when the episode starts low.
        riseGrace = hasStartPose ? RISE_GRACE * startPose.graceDepth() : 0.0;
        phaseStand = PHASE_STAND + riseGrace;
        phaseBalance = PHASE_BALANCE + riseGrace;
        nextPush = pushLevel > 0 ? phaseStand + 1.0 : std::numeric_limits<double>::infinity();

        // ---- the population ----
        walker.build(brain, M);
        walker.reset(this, spawn.x, spawn.z, startYaw, hasStartPose ? &startPose : nullptr);
        walker.timeLeft = (o.startBudget > 0 ? o.startBudget : START_BUDGET) + riseGrace;
        walker.rng.reseed(o.noiseSeed);

        time = 0; tick = 0; phase = Phase::STAND;
    }

    /* Next waypoint: a stride or two away, turned by at most the stage's limit.
     * Early stages keep the course nearly straight so a walker that can only go
     * forwards still scores; later ones make it turn. */
    Point spawnPoint() {
        const Point prev = points.empty() ? spawn : points.back();
        const double maxTurn = 0.35 + 1.6 * stage.turn;
        /* Some legs double back. Without this the course never turned more than
         * +/-47 degrees at stage 2, so a waypoint was always roughly ahead and the
         * hip-yaw joints were never under selection pressure. Never on the FIRST
         * leg: that one still has to be reachable by a newborn that can only
         * topple forwards, or the bottom of the ladder stops paying. */
        const bool spin = !points.empty() && pointRng() < stage.spin;
        const double PI = 3.141592653589793;
        const double h = spin
            // Behind, but not exactly astern — a dead-on reversal is a degenerate
            // case the walker could solve by falling backwards.
            ? lastHeading + PI + (pointRng()*2 - 1) * 0.7
            : lastHeading + (pointRng()*2 - 1) * maxTurn;
        const bool near = points.empty();
        const double d = near ? 1.3 + pointRng() * 1.0 : 2.2 + pointRng() * 2.2;
        /* On terrain stages, put the waypoint somewhere the ground is doing
         * something. Left to chance the course simply drifted, and since the turn
         * limit is narrow the whole leg could sit on one landing — the waypoints
         * appeared to spawn only on the level. Only hunt for relief once terrain
         * is part of the lesson: at stage 2 the ground is deliberately gentle, and
         * actively seeking the worst of it turned a 0.12 ceiling into 0.42 m
         * steps. */
        const bool wantRelief = stage.terrain >= 0.25;
        const int tries = wantRelief ? 6 : 1;
        Point best { 0, 0, 0 };
        double bestH = 0, bestRelief = -1;
        for (int i = 0; i < tries; i++) {
            /* Jitter, then clamp back INSIDE the cone this leg is allowed. The
             * first version added up to maxTurn/2 on top of an h that was already
             * up to maxTurn, so it reached 1.5x the stage limit — the comment
             * claimed the cone was never widened and the cone was widened. On a
             * turn-around leg there is no cone to respect. */
            double hj = h + (i == 0 ? 0.0 : (pointRng()*2 - 1) * maxTurn * 0.5);
            if (!spin && i > 0) {
                const double off = std::atan2(std::sin(hj - lastHeading), std::cos(hj - lastHeading));
                hj = lastHeading + std::max(-maxTurn, std::min(maxTurn, off));
            }
            const double dj = (i == 0) ? d : d * (0.75 + 0.5 * pointRng());
            Point c { prev.x + std::cos(hj)*dj, prev.z - std::sin(hj)*dj, 0 };
            c.y = terrain.height(c.x, c.z);
            // Height change over the leg, plus roughness sampled along it, so a
            // point across a flight beats one that merely ends higher.
            double relief = std::fabs(c.y - prev.y);
            for (int s = 1; s <= 3; s++) {
                const double t = s / 4.0;
                const double mx = prev.x + (c.x - prev.x)*t, mz = prev.z + (c.z - prev.z)*t;
                relief += std::fabs(terrain.height(mx, mz) - prev.y) * 0.5;
            }
            if (relief > bestRelief) { bestRelief = relief; best = c; bestH = hj; }
        }
        lastHeading = bestH;
        points.push_back(best);
        return best;
    }

    const Point& waypointFor(const Walker& w) {
        while ((size_t)w.legIdx >= points.size()) spawnPoint();
        return points[(size_t)w.legIdx];
    }

    void onArrival(Walker& w) {
        if (w.arrivals >= MAX_ARRIVALS) { w.done = true; return; }
        if (w.timeLeft > MAX_CLOCK) w.timeLeft = MAX_CLOCK;
        const Point& p = waypointFor(w);
        w.beginLeg(time, p.x, p.z);
    }

    void updWind() {
        if (!windOn) return;
        Rng& r = rng;
        windSpeed += (windTarget - windSpeed) * 0.004 + (r() - 0.5) * 0.25 * windFrac;
        windSpeed = std::max(0.0, std::min(windTarget * 1.8, windSpeed));
        windDir += (r() - 0.5) * 0.02;
        wind[0] = std::cos(windDir) * windSpeed;
        wind[2] = -std::sin(windDir) * windSpeed;
    }

    /* One shove, identical for every walker, so surviving it is skill not luck. */
    void maybePush() {
        if (time < nextPush) return;
        Rng& r = rng;
        const double mag = pushLevel * (60 + r() * 120);
        const double dir = r() * 3.141592653589793 * 2;
        const double fx = std::cos(dir) * mag, fz = std::sin(dir) * mag;
        if (!walker.done) {
            walker.pushX = fx; walker.pushZ = fz; walker.pushLeft = 0.12;
            walker.pendingPush = 1.5;
        }
        nextPush = time + 2.5 + r() * 3.5;
    }

    void step() {
        const bool controlTick = (tick % CONTROL_EVERY) == 0;
        const bool wasWalk = (phase == Phase::WALK);
        phase = time < phaseStand ? Phase::STAND : time < phaseBalance ? Phase::BALANCE : Phase::WALK;
        if (!wasWalk && phase == Phase::WALK && !walker.done) {
            const Point& p = waypointFor(walker);
            walker.beginLeg(time, p.x, p.z);
        }
        if (controlTick) {
            updWind();
            if (pushLevel > 0 && phase != Phase::STAND) maybePush();
            if (!walker.done) walker.control(*this);
        }
        if (!walker.done) walker.stepPhysics(*this, DT);
        if (controlTick && !walker.done) walker.tickBook(*this);
        time += DT;
        tick++;
    }

    bool isOver() const { return time >= EPISODE_HARD_CAP || walker.done; }
};
