// ══════════════════════════════════════════════════════
//  STOCKMAN – variables.js  (data ported from variables.py)
// ══════════════════════════════════════════════════════

const fictionalStocks = {
  "Food": ["Gourmet Foods","Healthy Eats","Snack World","Organic Delights","TastyTreats","Farm Fresh","Crispy Corners","Chef's Choice"],
  "Pharmaceutical": ["MediLife","PharmaPlus","CureCo","BioAdvance","HealthGen","LifeSavers Pharma","VaccineVenture","PillWorks"],
  "Tech": ["TechNova","CyberSoft","Quantum Systems","NanoLogic","DataSphere","FutureTek","SysX Innovations","NextGen Solutions","BlueChip Technologies"],
  "Energy": ["GreenEnergy","PowerGrid","Solaris Corp","EcoFuel","RenewGen","VoltWind","Terra Energy","FusionPower"],
  "Defense": ["DefendTech","SecureCorp","ShieldWorks","AeroDefense","ArmorCo","BattleGrid","Tactical Innovations","Vanguard Defense"],
  "Automotive": ["AutoDrive","Speedster Motors","HyperWheels","Electric Motion","TorqueMotors","FusionDrive","AutoFusion","Prime Motors"],
  "Entertainment": ["FunTime","StarMedia","MovieMagic","GameZone Studios","EpicCinema","DreamScape Productions","Spectra Entertainment","Big Screen Studios"],
  "Agriculture": ["AgriTech","Corn Company","Harvest Industries","GreenGroves","SeedGrow","FertileFields","EcoFarms","FreshSprouts"],
  "Fashion": ["StyleFusion","TrendWear","Couture House","Urban Outfitters","ChicDesigns","ModeWear","FashionFrenzy","RunwayStyles"],
  "Retail": ["ShopMore","QuickMart","MarketSpace","DealFinders","SuperBuy","DiscountPlus","RetailWorld","DailyNeeds"],
  "Finance": ["WealthPro","MoneyMakers","InvestMax","CreditLine Bank","CapitalVision","SafeInvest","BankOnIt","FortuneFund"],
  "Transportation": ["FastTrack","Transo Logistics","SkyCargo","MetroLink","JetExpress","CargoMove","HighwayHaul","RapidRoute"],
  "Healthcare": ["HealthGuard","Wellness Solutions","VitalMed","CareFirst","HealingHands","MediCareNet","LifeAid Health","Pathway Wellness"],
  "Telecommunications": ["GlobalNet","WaveComm","TalkSphere","SignalNow","CommConnect","TeleGrid","FastLink","SatNet Communications"],
  "Real Estate": ["UrbanSpace","Prime Properties","EstateBuilders","Skyline Ventures","BrickWorks Realty","HomeScape","SkyRise Developments","CityLiving"],
  "Consumer Goods": ["HomeEssentials","Bright Appliances","MegaClean","HappyHome","LivingLux","ComfortWare","FreshHome","FreshLife Products"],
  "Gaming": ["Pixel Play","Battle Arena","VirtualVerse","GameForge Studios","EliteGamers","RetroWave","Arcadia Games","FusionPlay"],
  "Biotech": ["GeneWorks","LifeGen","BioInnovations","Cellular Tech","MedGenome","BioQuest","NanoBiotics","CellFusion"],
  "Aerospace": ["StarFlight","OrbitCorp","AeroSpace Dynamics","LunarTech","NovaSpace","Cosmo Ventures","Stratos Systems","AstroFlight"],
  "Hospitality": ["GlobalStays","Luxury Resorts","CityEscapes","Zen Hotels","OceanView Resorts","DreamStay Hotels","Sunrise Hospitality","EcoLodge"],
  "Insurance": ["SafeGuard Insurance","LifeSecure","ProtectPlus","SureShield","CoverAll","RiskGuard","InsureNow","PrimeCare"],
  "E-commerce": ["BuyNow","ShopNet","InstantDeals","QuickCart","E-Shop World","CartPlus","OnlineBazaar","WebMall"],
  "Media": ["InfoStream","NewsNow","PulseMedia","GlobalNews","FastWire","BuzzNet","PrimeReport","UpdateX Media"],
  "Construction": ["BuildMax","SteelWorks","MegaConstruct","Concrete Solutions","Skyline Builders","SolidBase","PrimeConstruct","UrbanBuild"],
  "Chemicals": ["ChemCo","FusionChem","BioChemTech","SafeChem","Johnson Compounds","ElementalTech","SynthoSolutions","InnovativeChem"],
  "Mining": ["GoldWorks","RockSolid Mining","TerraMines","MineralMax","IronStone","DeepDigs","GlobalExtraction","Gemstone Resources"],
  "Logistics": ["QuickShip","CargoFleet","TransLogix","EasyFreight","ShipIt Logistics","GlobalFreight","SpeedyShip","LogiMax"],
  "Education": ["BrightMinds","FutureLearn","Global Academy","EduCorp","KnowledgePath","SkillPro","MentorMe","NextStep Learning"],
  "Luxury Goods": ["EliteDesigns","GoldenTouch","DiamondWorks","LuxuryEssentials","PrestigeLuxe","RoyalCollection","VelvetCraft","Opulent Brands"],
};

const newsDict = {
  "NextGen Solutions introduces revolutionary home computer, stock soars": ["Stock","NextGen Solutions",1],
  "Automotive sector accelerates as demand for muscle cars revs up": ["Category","Automotive",1],
  "Arcadia Games' latest console causes craze; lines wrap around city blocks": ["Stock","Arcadia Games",1],
  "Tech sector rattled by floppy disk shortage halting production": ["Category","Tech",-1.5],
  "BioAdvance claims cure for common cold; scientists skeptical": ["Stock","BioAdvance",1],
  "Energy sector boosted by discovery of massive oil reserves in Alaska": ["Category","Energy",1],
  "NanoLogic's microchip breakthrough doubles computing power": ["Stock","NanoLogic",1],
  "Fashion industry dazzled as neon colors dominate runways": ["Category","Fashion",1],
  "FusionDrive unveils sports car breaking speed records": ["Stock","FusionDrive",1],
  "Media sector abuzz over VHS tapes revolutionizing home entertainment": ["Category","Media",1],
  "DefendTech accused of selling outdated equipment to military": ["Stock","DefendTech",-1.5],
  "Healthcare sector faces scrutiny over rising insurance premiums": ["Category","Healthcare",-1.5],
  "WaveComm's mobile phone becomes ultimate status symbol despite size": ["Stock","WaveComm",1],
  "Mining sector hit by labor strikes across multiple countries": ["Category","Mining",-1.5],
  "BankOnIt faces allegations of insider trading": ["Stock","BankOnIt",-1.5],
  "RetailWorld announces 'biggest sale ever'; shoppers rejoice": ["Stock","RetailWorld",1],
  "FastLink's new pager expected to change communication forever": ["Stock","FastLink",1],
  "LuxuryEssentials sells out limited edition watches in record time": ["Stock","LuxuryEssentials",1],
  "Gaming sector shaken by video game crash; companies scramble": ["Category","Gaming",-1.5],
  "PharmaPlus's diet pill promises miracles; FDA expresses concern": ["Stock","PharmaPlus",-1.5],
  "Transportation sector celebrates as new highway reduces travel times": ["Category","Transportation",1],
  "EcoFuel develops alternative fuel from algae; stock rises": ["Stock","EcoFuel",1],
  "Entertainment sector thrives with blockbuster summer hits": ["Category","Entertainment",1],
  "StarMedia's latest film breaks box office records": ["Stock","StarMedia",1],
  "Automotive sector fears imports as Japanese cars gain popularity": ["Category","Automotive",-1.5],
  "TorqueMotors recalls vehicles over safety concerns": ["Stock","TorqueMotors",-1.5],
  "Food sector sees surge in microwave meal popularity": ["Category","Food",1],
  "Gourmet Foods launches line of instant dinners": ["Stock","Gourmet Foods",1],
  "Finance sector excited as stock market reaches all-time high": ["Category","Finance",1],
  "WealthPro introduces revolutionary investment strategy": ["Stock","WealthPro",1],
  "Telecommunications sector expands with fiber optic advancements": ["Category","Telecommunications",1],
  "GlobalNet connects cities with high-speed internet": ["Stock","GlobalNet",1],
  "Agriculture sector struggles with farm debt crisis": ["Category","Agriculture",-1.5],
  "Harvest Industries faces bankruptcy amid economic downturn": ["Stock","Harvest Industries",-1.5],
  "Energy sector worried as oil prices plummet": ["Category","Energy",-1.5],
  "PowerGrid's profits decline due to cheaper alternatives": ["Stock","PowerGrid",-1.5],
  "DefendTech secures billion-dollar defense contract": ["Stock","DefendTech",1],
  "FashionFrenzy launches iconic denim line; becomes instant hit": ["Stock","FashionFrenzy",1],
  "E-commerce sector in infancy; skeptics doubt its future": ["Category","E-commerce",-1.5],
  "BuyNow pioneers online shopping experience": ["Stock","BuyNow",1],
  "Healthcare sector optimistic with new medical technologies": ["Category","Healthcare",1],
  "LifeAid Health introduces MRI machines to hospitals": ["Stock","LifeAid Health",1],
  "Insurance sector faces claims after natural disasters": ["Category","Insurance",-1.5],
  "SafeGuard Insurance handles record number of claims": ["Stock","SafeGuard Insurance",-1.5],
  "Construction sector booms with urban development projects": ["Category","Construction",1],
  "Skyline Builders awarded contract for tallest skyscraper": ["Stock","Skyline Builders",1],
  "TechNova develops compact disc technology; changes music industry": ["Stock","TechNova",1],
  "Media sector shifts focus to 14-hour news cycles": ["Category","Media",1],
  "NewsNow launches around-the-clock broadcasting": ["Stock","NewsNow",1],
  "Automotive sector experiments with hydrogen fuel cells": ["Category","Automotive",0.5],
  "Electric Motion invests heavily in alternative energy vehicles": ["Stock","Electric Motion",1],
  "Pharmaceutical sector advances with AIDS research": ["Category","Pharmaceutical",1],
  "MediLife's new treatment offers hope to patients": ["Stock","MediLife",1],
  "Entertainment sector faces backlash over violent content": ["Category","Entertainment",-1.5],
  "EpicCinema delays controversial film release": ["Stock","EpicCinema",-1.5],
  "Logistics sector revolutionized by barcode scanning": ["Category","Logistics",1],
  "QuickShip implements new tracking system; increases efficiency": ["Stock","QuickShip",1],
  "Telecommunications sector excited over satellite phone prospects": ["Category","Telecommunications",1],
  "SatNet Communications launches first mobile satellite": ["Stock","SatNet Communications",1],
  "Mining sector benefits from high demand for precious metals": ["Category","Mining",1],
  "Gemstone Resources discovers large diamond deposit": ["Stock","Gemstone Resources",1],
  "Retail sector threatened by big-box store expansion": ["Category","Retail",-1.5],
  "DailyNeeds struggles to compete with larger chains": ["Stock","DailyNeeds",-1.5],
  "Fashion industry embraces shoulder pads; consumers perplexed": ["Category","Fashion",1],
  "Urban Outfitters capitalizes on latest fashion trends": ["Stock","Urban Outfitters",1],
  "Transportation sector excited about Concorde's supersonic flights": ["Category","Transportation",1],
  "SkyCargo explores high-speed cargo delivery": ["Stock","SkyCargo",1],
  "Chemicals sector faces environmental regulation challenges": ["Category","Chemicals",-1.5],
  "SafeChem fined for pollution violations": ["Stock","SafeChem",-1.5],
  "Education sector expands with computer-based learning": ["Category","Education",1],
  "EduCorp introduces PCs into classrooms": ["Stock","EduCorp",1],
  "Hospitality sector thrives with rise of luxury resorts": ["Category","Hospitality",1],
  "OceanView Resorts opens new location in the Caribbean": ["Stock","OceanView Resorts",1],
  "Finance sector cautious as savings and loan crisis unfolds": ["Category","Finance",-1.5],
  "MoneyMakers affected by banking regulations": ["Stock","MoneyMakers",-1.5],
  "Food sector innovates with 'low-fat' products": ["Category","Food",1],
  "Healthy Eats launches successful line of diet foods": ["Stock","Healthy Eats",1],
  "Gaming sector revives with introduction of 16-bit consoles": ["Category","Gaming",1],
  "Battle Arena releases game that defines a generation": ["Stock","Battle Arena",1],
  "Telecommunications sector competes over long-distance calling rates": ["Category","Telecommunications",-1.5],
  "CommConnect undercuts competitors with lower rates": ["Stock","CommConnect",1],
  "Real Estate market booms with suburban expansion": ["Category","Real Estate",1],
  "Prime Properties sells out new housing development": ["Stock","Prime Properties",1],
  "Consumer Goods sector benefits from 'as seen on TV' craze": ["Category","Consumer Goods",1],
  "Bright Appliances' new gadget becomes household staple": ["Stock","Bright Appliances",1],
  "Biotech sector explores genetic engineering possibilities": ["Category","Biotech",1],
  "GeneWorks pioneers gene splicing techniques": ["Stock","GeneWorks",1],
  "Aerospace sector excited by Space Shuttle launches": ["Category","Aerospace",1],
  "StarFlight collaborates with NASA on new missions": ["Stock","StarFlight",1],
  "Insurance sector adapts to increased life expectancy": ["Category","Insurance",1],
  "LifeSecure offers new long-term policies": ["Stock","LifeSecure",1],
  "E-commerce concept met with skepticism by traditional retailers": ["Category","E-commerce",-1.5],
  "InstantDeals tries to convince investors of online potential": ["Stock","InstantDeals",-1.5],
  "Media sector faces challenges from cable television rise": ["Category","Media",-1.5],
  "InfoStream loses viewers to specialized channels": ["Stock","InfoStream",-1.5],
  "Construction sector hit by asbestos regulation changes": ["Category","Construction",-1.5],
  "Concrete Solutions halts projects for safety inspections": ["Stock","Concrete Solutions",-1.5],
  "Chemicals sector explores plastics for new applications": ["Category","Chemicals",1],
  "Johnson Compounds develops stronger, lighter materials": ["Stock","Johnson Compounds",1],
  "Mining sector faces equipment shortages": ["Category","Mining",-1.5],
  "DeepDigs delays operations due to machinery issues": ["Stock","DeepDigs",-1.5],
  "Logistics sector booms with globalization trends": ["Category","Logistics",1],
  "GlobalFreight expands routes to Asia": ["Stock","GlobalFreight",1],
  "Education sector debates standardized testing merits": ["Category","Education",-1.5],
  "KnowledgePath advocates for alternative assessments": ["Stock","KnowledgePath",1],
  "Luxury Goods sector flourishes with high consumer confidence": ["Category","Luxury Goods",1],
  "GoldenTouch's jewelry sales hit record highs": ["Stock","GoldenTouch",1],
  "Food sector hit by concerns over preservatives": ["Category","Food",-1.5],
  "Organic Delights gains popularity amid health scares": ["Stock","Organic Delights",1],
  "Pharmaceutical sector develops groundbreaking antibiotics": ["Category","Pharmaceutical",1],
  "CureCo's new drug fights resistant bacteria": ["Stock","CureCo",1],
  "Tech sector excited by rise of personal computing": ["Category","Tech",1],
  "BlueChip Technologies dominates PC market": ["Stock","BlueChip Technologies",1],
  "Energy sector worried about nuclear power perception": ["Category","Energy",-1.5],
  "FusionPower reassures public after minor plant incident": ["Stock","FusionPower",-1.5],
  "Defense sector bolstered by increased military spending": ["Category","Defense",1],
  "ArmorCo's stock rises with new government contracts": ["Stock","ArmorCo",1],
  "Automotive sector explores turbocharged engines": ["Category","Automotive",1],
  "Speedster Motors introduces turbo model; enthusiasts thrilled": ["Stock","Speedster Motors",1],
  "Entertainment sector embraces MTV generation": ["Category","Entertainment",1],
  "DreamScape Productions produces hit music videos": ["Stock","DreamScape Productions",1],
  "Agriculture sector adapts to high-tech equipment": ["Category","Agriculture",1],
  "SeedGrow develops automated planting systems": ["Stock","SeedGrow",1],
  "Fashion industry shocked by 'grunge' style emergence": ["Category","Fashion",-1.5],
  "Couture House struggles to adapt to changing tastes": ["Stock","Couture House",-1.5],
  "Retail sector benefits from mall culture explosion": ["Category","Retail",1],
  "QuickMart opens stores in major shopping centers": ["Stock","QuickMart",1],
  "Finance sector enjoys profits from junk bond sales": ["Category","Finance",1],
  "CapitalVision invests heavily in high-yield bonds": ["Stock","CapitalVision",1],
  "Transportation sector sees rise in air travel demand": ["Category","Transportation",1],
  "MetroLink expands services to additional cities": ["Stock","MetroLink",1],
  "Healthcare sector debates HMOs and patient care": ["Category","Healthcare",-1.5],
  "Pathway Wellness advocates for patient rights": ["Stock","Pathway Wellness",1],
  "Telecommunications sector faces breakup of monopolies": ["Category","Telecommunications",-1.5],
  "TeleGrid adjusts strategies post-regulation changes": ["Stock","TeleGrid",-1.5],
  "Real Estate sector concerned over bubble warnings": ["Category","Real Estate",-1.5],
  "EstateBuilders slows down new projects amid market fears": ["Stock","EstateBuilders",-1.5],
  "Consumer Goods sector capitalizes on fitness craze": ["Category","Consumer Goods",1],
  "ComfortWare's athletic apparel sees increased sales": ["Stock","ComfortWare",1],
  "Gaming sector faces parental backlash over content": ["Category","Gaming",-1.5],
  "FusionPlay implements rating system to appease critics": ["Stock","FusionPlay",1],
  "Biotech sector explores cloning possibilities": ["Category","Biotech",1],
  "CellFusion's cloning experiments spark ethical debates": ["Stock","CellFusion",-0.5],
  "Aerospace sector mourns after Challenger disaster": ["Category","Aerospace",-1.5],
  "AeroSpace Dynamics reassesses safety protocols": ["Stock","AeroSpace Dynamics",-1.5],
  "Hospitality sector adapts to business traveler needs": ["Category","Hospitality",1],
  "CityEscapes opens executive suites in major cities": ["Stock","CityEscapes",1],
  "Insurance sector deals with increased healthcare costs": ["Category","Insurance",-1.5],
  "SureShield raises premiums to cover expenses": ["Stock","SureShield",-1.5],
  "E-commerce sector overlooked as 'just a fad'": ["Category","E-commerce",-1.5],
  "QuickCart insists online shopping is the future": ["Stock","QuickCart",-1.5],
  "Media sector embraces talk radio popularity": ["Category","Media",1],
  "FastWire launches syndicated radio programs": ["Stock","FastWire",1],
  "Construction sector faces labor shortages": ["Category","Construction",-1.5],
  "SolidBase increases wages to attract workers": ["Stock","SolidBase",-1.5],
  "Chemicals sector improves safety standards": ["Category","Chemicals",1],
  "ElementalTech invests in employee training": ["Stock","ElementalTech",1],
  "Mining sector explores automation to increase output": ["Category","Mining",1],
  "IronStone invests in robotic mining equipment": ["Stock","IronStone",1],
  "Logistics sector utilizes GPS technology": ["Category","Logistics",1],
  "CargoFleet improves delivery times with new tech": ["Stock","CargoFleet",1],
  "Education sector debates 'new math' curriculum": ["Category","Education",-1.5],
  "MentorMe supports traditional teaching methods": ["Stock","MentorMe",1],
  "Luxury Goods sector hurt by economic recession": ["Category","Luxury Goods",-1.5],
  "PrestigeLuxe reports decline in sales": ["Stock","PrestigeLuxe",-1.5],
  "Food sector experiences coffee shortage": ["Category","Food",-1.5],
  "Farm Fresh raises prices due to supply issues": ["Stock","Farm Fresh",-1.5],
  "Pharmaceutical sector investigates natural remedies": ["Category","Pharmaceutical",1],
  "PillWorks releases herbal supplement line": ["Stock","PillWorks",1],
  "Tech sector anticipates Y1K bug challenges": ["Category","Tech",-1.5],
  "SysX Innovations offers solutions to Y1K problem": ["Stock","SysX Innovations",1],
  "Energy sector considers wind power investments": ["Category","Energy",1],
  "VoltWind builds first large-scale wind farm": ["Stock","VoltWind",1],
  "Defense sector develops stealth technology": ["Category","Defense",1],
  "ShieldWorks unveils new stealth aircraft": ["Stock","ShieldWorks",1],
  "Automotive sector excited by SUV popularity": ["Category","Automotive",1],
  "AutoDrive's new SUV becomes best-seller": ["Stock","AutoDrive",1],
  "Entertainment sector shifts focus to reality TV": ["Category","Entertainment",1],
  "Spectra Entertainment launches hit reality show": ["Stock","Spectra Entertainment",1],
  "Agriculture sector benefits from GMO crops": ["Category","Agriculture",1],
  "EcoFarms adopts GMO seeds to increase yield": ["Stock","EcoFarms",1],
  "Fashion industry goes minimalist; 'less is more'": ["Category","Fashion",1],
  "RunwayStyles leads with simple designs": ["Stock","RunwayStyles",1],
  "Retail sector embraces loyalty programs": ["Category","Retail",1],
  "DealFinders' rewards program attracts customers": ["Stock","DealFinders",1],
  "Finance sector faces competition from fintech startups": ["Category","Finance",-1.5],
  "FortuneFund invests in new technologies": ["Stock","FortuneFund",1],
  "Transportation sector looks into magnetic levitation trains": ["Category","Transportation",1],
  "HighwayHaul explores maglev tech for freight": ["Stock","HighwayHaul",1],
  "Healthcare sector deals with malpractice lawsuits": ["Category","Healthcare",-1.5],
  "HealingHands implements stricter protocols": ["Stock","HealingHands",-1.5],
  "Telecommunications sector tests video calling capabilities": ["Category","Telecommunications",1],
  "SignalNow pioneers early video conferencing": ["Stock","SignalNow",1],
  "Real Estate sector adapts to 'McMansion' trend": ["Category","Real Estate",1],
  "UrbanSpace builds larger suburban homes": ["Stock","UrbanSpace",1],
  "Consumer Goods sector faces backlash over sweatshops": ["Category","Consumer Goods",-1.5],
  "FreshLife Products commits to ethical sourcing": ["Stock","FreshLife Products",1],
  "Gaming sector experiments with virtual reality": ["Category","Gaming",0.75],
  "Pixel Play develops early VR headset prototype": ["Stock","Pixel Play",1],
  "Biotech sector researches human genome mapping": ["Category","Biotech",1],
  "MedGenome contributes to Human Genome Project": ["Stock","MedGenome",1],
  "Aerospace sector tests reusable spacecraft": ["Category","Aerospace",1],
  "NovaSpace designs shuttle for multiple missions": ["Stock","NovaSpace",1],
  "Hospitality sector caters to eco-tourism demand": ["Category","Hospitality",1],
  "Zen Hotels opens eco-friendly locations": ["Stock","Zen Hotels",1],
  "Insurance sector offers bundled policies": ["Category","Insurance",1],
  "CoverAll's package deals attract new clients": ["Stock","CoverAll",1],
  "E-commerce sector gains traction with young consumers": ["Category","E-commerce",1],
  "ShopNet reports increase in online sales": ["Stock","ShopNet",1],
  "Media sector explores satellite radio possibilities": ["Category","Media",1],
  "UpdateX Media invests in satellite technology": ["Stock","UpdateX Media",1],
  "Construction sector adopts CAD software": ["Category","Construction",1],
  "PrimeConstruct reduces design time with new tools": ["Stock","PrimeConstruct",1],
  "Chemicals sector faces competition from overseas": ["Category","Chemicals",-1.5],
  "SynthoSolutions cuts costs to remain competitive": ["Stock","SynthoSolutions",-1.5],
  "Mining sector benefits from increased gold prices": ["Category","Mining",1],
  "GlobalExtraction expands operations in Africa": ["Stock","GlobalExtraction",1],
  "Logistics sector tests RFID tracking": ["Category","Logistics",1],
  "SpeedyShip improves inventory management": ["Stock","SpeedyShip",1],
  "Education sector invests in teacher training": ["Category","Education",1],
  "SkillPro offers workshops to educators": ["Stock","SkillPro",1],
  "Luxury Goods sector partners with fashion houses": ["Category","Luxury Goods",1],
  "VelvetCraft collaborates with top designers": ["Stock","VelvetCraft",1],
  "TechNova launches first commercially successful CD player, stock skyrockets": ["Stock","TechNova",1],
  "Food sector rattled by unexpected rise in margarine prices": ["Category","Food",-1.5],
  "Gourmet Foods introduces 'chocolate-covered broccoli'; consumers baffled": ["Stock","Gourmet Foods",-1.5],
  "PharmaPlus secures FDA approval for new heart medication": ["Stock","PharmaPlus",1],
  "BioAdvance's laboratory accidentally creates super-strong adhesive, stock jumps": ["Stock","BioAdvance",1],
  "Energy sector excited by booming nuclear power investments": ["Category","Energy",1],
  "Solaris Corp's solar panels catch fire during demonstration, stock plummets": ["Stock","Solaris Corp",-1.5],
  "DefendTech's new laser defense system hailed as 'unnecessary but cool'": ["Stock","DefendTech",1],
  "SecureCorp faces unexpected data breach, investor confidence shaken": ["Stock","SecureCorp",-1.5],
  "Automotive sector celebrates the introduction of self-driving cars… in theory": ["Category","Automotive",1],
  "AutoDrive's prototype self-driving car fails spectacularly during test drive": ["Stock","AutoDrive",-1.5],
  "Entertainment sector thrills with the release of the first-ever CD-ROM games": ["Category","Entertainment",1],
  "GameZone Studios accidentally releases unfinished game, players frustrated": ["Stock","GameZone Studios",-1.5],
  "Agriculture sector benefits from genetically modified crops increasing yields": ["Category","Agriculture",1],
  "Corn Company faces backlash over GMO corn, sales dip": ["Stock","Corn Company",-1.5],
  "Fashion sector dazzles with the comeback of shoulder pads and big hair": ["Category","Fashion",1],
  "StyleFusion's oversized blazers become overnight fashion sensation": ["Stock","StyleFusion",1],
  "Retail sector hit by shortage of neon signage materials": ["Category","Retail",-1.5],
  "QuickMart runs out of popular cassette tapes, customers irate": ["Stock","QuickMart",-1.5],
  "Finance sector optimistic as Wall Street hits new heights": ["Category","Finance",1],
  "InvestMax predicts bull market for next decade, investors ecstatic": ["Stock","InvestMax",1],
  "Transportation sector struggles with rising fuel costs affecting profitability": ["Category","Transportation",-1.5],
  "SkyCargo's new jumbo jets face delays, stock declines": ["Stock","SkyCargo",-1.5],
  "Healthcare sector applauds advances in MRI technology improving diagnostics": ["Category","Healthcare",1],
  "Wellness Solutions' new fitness craze leads to surge in gym memberships": ["Stock","Wellness Solutions",1],
  "Telecommunications sector overwhelmed by unexpected surge in fax machine sales": ["Category","Telecommunications",1],
  "TalkSphere's latest fax machine model malfunctions, returns increase": ["Stock","TalkSphere",-1.5],
  "Real Estate sector flourishes with the rise of suburban developments": ["Category","Real Estate",1],
  "UrbanSpace's new suburban complexes sell out within weeks": ["Stock","UrbanSpace",1],
  "Consumer Goods sector faces criticism over excessive use of plastic packaging": ["Category","Consumer Goods",-1.5],
  "MegaClean launches eco-friendly cleaning products, gains market share": ["Stock","MegaClean",1],
  "Gaming sector ecstatic as 16-bit consoles dominate the market": ["Category","Gaming",1],
  "VirtualVerse's 16-bit adventure game becomes instant classic": ["Stock","VirtualVerse",1],
  "Biotech sector explores controversial gene therapy techniques": ["Category","Biotech",-1.5],
  "GeneWorks' gene therapy trial shows promising results, stock rises": ["Stock","GeneWorks",1],
  "Aerospace sector celebrates successful Space Shuttle mission": ["Category","Aerospace",1],
  "StarFlight's Space Shuttle launch faces minor technical issues but succeeds": ["Stock","StarFlight",1],
  "Hospitality sector thrives with the opening of new mega-resorts": ["Category","Hospitality",1],
  "GlobalStays' new mega-resort becomes the talk of the town": ["Stock","GlobalStays",1],
  "Insurance sector faces higher claims after severe winter storm": ["Category","Insurance",-1.5],
  "ProtectPlus offers innovative home insurance packages, attracting new clients": ["Stock","ProtectPlus",1],
  "E-commerce sector struggles with low consumer trust in online shopping": ["Category","E-commerce",-1.5],
  "BuyNow pioneers secure online payment systems, boosting consumer confidence": ["Stock","BuyNow",1],
  "Media sector experiences boom with the rise of cable TV networks": ["Category","Media",1],
  "NewsNow's 14-hour news channel attracts millions of viewers": ["Stock","NewsNow",1],
  "Construction sector hit by rising costs of steel and concrete": ["Category","Construction",-1.5],
  "BuildMax innovates with cost-effective construction techniques, stock climbs": ["Stock","BuildMax",1],
  "Chemicals sector faces backlash over hazardous waste disposal practices": ["Category","Chemicals",-1.5],
  "FusionChem develops non-toxic chemical alternatives, regains public trust": ["Stock","FusionChem",1],
  "Mining sector thrives with soaring gold prices": ["Category","Mining",1],
  "GoldWorks discovers new gold vein, stock surges": ["Stock","GoldWorks",1],
  "Logistics sector embraces barcode technology for efficient tracking": ["Category","Logistics",1],
  "CargoFleet implements barcode system, reduces delivery errors": ["Stock","CargoFleet",1],
  "Education sector debates the introduction of personal computers in classrooms": ["Category","Education",1],
  "BrightMinds secures funding for computer-based learning programs": ["Stock","BrightMinds",1],
  "Luxury Goods sector dazzles with the launch of diamond-encrusted gadgets": ["Category","Luxury Goods",1],
  "DiamondWorks releases diamond-studded wristwatch, becomes status symbol": ["Stock","DiamondWorks",1],
  "Food sector celebrates the introduction of microwave ovens revolutionizing cooking": ["Category","Food",1],
  "Healthy Eats launches microwave-ready healthy meal options, sales soar": ["Stock","Healthy Eats",1],
  "Pharmaceutical sector faces patent cliffs affecting major drug revenues": ["Category","Pharmaceutical",-1.5],
  "CureCo develops new drug extending patent life, stock rebounds": ["Stock","CureCo",1],
  "Tech sector overwhelmed by rapid obsolescence of hardware": ["Category","Tech",-1.5],
  "DataSphere's innovative hardware redesign extends product lifecycle": ["Stock","DataSphere",1],
  "Energy sector explores offshore drilling opportunities": ["Category","Energy",1],
  "VoltWind's offshore wind farm project approved, stock rises": ["Stock","VoltWind",1],
  "Defense sector benefits from increased military contracts": ["Category","Defense",1],
  "Vanguard Defense secures lucrative defense contracts, stock soars": ["Stock","Vanguard Defense",1],
  "Automotive sector hits roadblocks with rising environmental regulations": ["Category","Automotive",-1.5],
  "Electric Motion adapts to regulations with eco-friendly vehicle lineup": ["Stock","Electric Motion",1],
  "Entertainment sector thrilled by the blockbuster success of 'Back to the Future'": ["Category","Entertainment",1],
  "EpicCinema's 'Back to the Future' sees record-breaking ticket sales": ["Stock","EpicCinema",1],
  "Agriculture sector struggles with invasive pest species affecting crops": ["Category","Agriculture",-1.5],
  "FertileFields develops pest-resistant crops, mitigating losses": ["Stock","FertileFields",1],
  "Fashion sector lambasts oversized accessories trend": ["Category","Fashion",-1.5],
  "ModeWear counters with sleek, minimalist accessory line, gaining popularity": ["Stock","ModeWear",1],
  "Retail sector sees decline in mall foot traffic due to rising online sales": ["Category","Retail",-1.5],
  "SuperBuy integrates online shopping with physical stores, reversing decline": ["Stock","SuperBuy",1],
  "Finance sector alarmed by rising interest rates impacting loans": ["Category","Finance",-1.5],
  "CapitalVision hedges investments to protect against interest rate hikes": ["Stock","CapitalVision",1],
  "Transportation sector excited by advancements in high-speed trains": ["Category","Transportation",1],
  "RapidRoute unveils high-speed train prototype, stock jumps": ["Stock","RapidRoute",1],
  "Healthcare sector celebrates breakthroughs in cancer treatment research": ["Category","Healthcare",1],
  "VitalMed's new cancer drug receives rave reviews, stock soars": ["Stock","VitalMed",1],
  "Telecommunications sector faces unexpected surge in landline sales": ["Category","Telecommunications",1],
  "CommConnect capitalizes on landline boom with innovative service packages": ["Stock","CommConnect",1],
  "Real Estate sector fears bubble as prices skyrocket uncontrollably": ["Category","Real Estate",-1.5],
  "BrickWorks Realty implements cooling measures, stabilizes growth": ["Stock","BrickWorks Realty",0.5],
  "Consumer Goods sector thrives with rise of home entertainment systems": ["Category","Consumer Goods",1],
  "HappyHome's new home theater systems become household must-have": ["Stock","HappyHome",1],
  "Gaming sector faces criticism over excessive violence in video games": ["Category","Gaming",-1.5],
  "Battle Arena introduces content rating system, appeasing critics": ["Stock","Battle Arena",1],
  "Biotech sector explores synthetic biology, pushing ethical boundaries": ["Category","Biotech",-1.5],
  "Cellular Tech's synthetic biology breakthroughs attract major investments": ["Stock","Cellular Tech",1],
  "Aerospace sector dazzled by commercial space travel prospects": ["Category","Aerospace",1],
  "NovaSpace announces first commercial space tourism flight, stock rockets": ["Stock","NovaSpace",1],
  "Hospitality sector innovates with themed hotels attracting niche markets": ["Category","Hospitality",1],
  "Sunrise Hospitality's pirate-themed hotel opens to rave reviews": ["Stock","Sunrise Hospitality",1],
  "Insurance sector struggles with rising healthcare-related claims": ["Category","Insurance",-1.5],
  "InsureNow launches comprehensive health insurance packages, gaining clients": ["Stock","InsureNow",1],
  "E-commerce sector experiences growing pains with first major data breaches": ["Category","E-commerce",-2.5],
  "WebMall enhances security measures after recent breaches, regains trust": ["Stock","WebMall",1.5],
  "Media sector buzzed by the rise of reality TV shows": ["Category","Media",1],
  "PrimeReport's new reality show becomes overnight sensation": ["Stock","PrimeReport",1],
  "Construction sector overcomes labor shortages with innovative training programs": ["Category","Construction",1],
  "UrbanBuild's apprenticeship program reduces labor shortages, boosts productivity": ["Stock","UrbanBuild",1],
  "Chemicals sector faces scrutiny over toxic emissions from factories": ["Category","Chemicals",-1.5],
  "InnovativeChem's green chemistry initiatives improve public image": ["Stock","InnovativeChem",1],
  "Mining sector reaps rewards from rare earth metals demand": ["Category","Mining",1],
  "RockSolid Mining secures rare earth metals contract, stock surges": ["Stock","RockSolid Mining",1],
  "Logistics sector innovates with early GPS navigation systems": ["Category","Logistics",1],
  "TransLogix's GPS integration reduces delivery times significantly": ["Stock","TransLogix",1],
  "Education sector embraces distance learning technologies": ["Category","Education",1],
  "NextStep Learning's online courses attract global students": ["Stock","NextStep Learning",1],
  "Luxury Goods sector faces decline as economic downturn affects spending": ["Category","Luxury Goods",-1.5],
  "Opulent Brands introduces affordable luxury line to capture broader market": ["Stock","Opulent Brands",1],
};

const graphTimeScales = {
  "1 day": 10,
  "1 week": 110,
  "1 month": 900,
  "6 months": 5400,
  "history": null,
};

const cheesySlogans = [
  "Can you beat the market?",
  "You could be the next stock man!",
  "Think you've got what it takes to own Wall Street?",
  "The bulls are running… Are you?",
  "Fortune favors the bold! Ready to cash in?",
  "Buy low, sell high, live fast!",
  "Money never sleeps… and neither should you!",
  "The stock market waits for no one!",
  "Feeling lucky? Spin the financial wheel!",
  "Only the fearless survive the trading floor!",
  "Could you be the next Master of the Market?",
  "From rags to riches… if you play it right!",
  "Don't just watch the ticker… be the ticker!",
  "Stocks are climbing… Are you?",
  "Trade fast, live large, retire rich!",
  "Welcome to the world of high stakes and high rewards!",
  "Cash in, cash out—make the market yours!",
  "Fortunes are made in minutes! Is yours one of them?",
  "The market is your playground… time to swing!",
  "Risk it all for the big win!",
  "It's a stock jungle out there. Can you be the king?",
  "From the trading floor to the penthouse!",
  "Will your portfolio stand the test of time?",
  "Market glory awaits the brave!",
  "When the bell rings, the game begins!",
  "Fortune is just a trade away!",
  "The hustle never stops on Wall Street!",
  "You can't win if you don't play!",
  "Chase your dreams, one stock at a time!",
  "Do you have the guts to go all in?",
  "This is where fortunes are forged!",
  "Step up, trade hard, and take charge!",
  "The ticker's ticking—time to make a move!",
  "Can you handle the heat of the trading floor?",
  "From small-time to big-time… are you ready?",
  "Who needs luck when you have strategy?",
  "Trade like a shark, feast like a king!",
  "One trade can change everything!",
  "The market is wild—are you bold enough?",
  "The stock market is your battlefield!",
  "Turn your pennies into millions!",
  "Step into the ring and take on the market!",
  "Profit is the name of the game!",
  "The market is your stage—time to perform!",
  "Watch your wealth soar as you master the market!",
  "In the world of stocks, only the strongest survive!",
  "Ready to dance with the bulls and bears?",
  "The power to win is in your hands!",
  "Your future fortune starts now!",
  "Wall Street isn't for the faint of heart!",
  "Fortune smiles on the brave traders!",
  "Cash in, cash out—make every second count!",
  "The clock is ticking… are you trading?",
  "The game is simple: buy, sell, profit!",
  "One trade, one shot, one chance to win big!",
  "Fortunes rise and fall… but will you?",
  "It's your turn to ride the market wave!",
  "The market is alive—are you in the game?",
  "Make moves, make money, make history!",
  "Big risks, bigger rewards… are you in?",
  "You can be a Wall Street legend!",
  "The stock market is your canvas—paint your masterpiece!",
  "Ready to build your empire, one trade at a time?",
  "There's no such thing as too bold in the market!",
  "Fortunes favor the traders who dare!",
  "Your next move could make you a millionaire!",
  "Don't just play the game… own it!",
  "Can you conquer the market chaos?",
  "Will you be the next market maverick?",
  "Turn your dreams into dividends!",
  "The market is moving… are you?",
];
