/* brainfile.js — read a brain from either kind of file this project produces.
 *
 * There are two, and they hold the same object with a different wrapper:
 *
 *   training/checkpoint.json   plain JSON, written by train.js while it runs
 *   default_brain.js           `window.DEFAULT_BRAIN = {...};`, what the page loads
 *
 * Every Node tool here accepts both, and that is deliberate rather than tidy.
 * `training/` is scratch space — it is regenerated by whichever run you are
 * doing and is not committed. The baked brain IS committed, so it is the only
 * file guaranteed to be present in a fresh clone. A tool that can only read a
 * checkpoint is a tool that stops working the moment someone cleans up.
 */
"use strict";
const fs = require("fs");
const path = require("path");

function loadBrainFile(p) {
    const full = path.isAbsolute(p) ? p : path.join(__dirname, p);
    const raw = fs.readFileSync(full, "utf8");
    let txt = raw;
    if (!/\.json$/i.test(full)) {
        // Baked file: skip the header comment and the assignment, then take the
        // object literal. Anchoring the search on the `=` rather than on the
        // first `{` in the file means a brace in the comment cannot break it.
        const eq = raw.indexOf("=");
        const start = raw.indexOf("{", eq >= 0 ? eq : 0);
        const end = raw.lastIndexOf("}");
        if (start < 0 || end < start) throw new Error(`${p}: no brain object found`);
        txt = raw.slice(start, end + 1);
    }
    const o = JSON.parse(txt);
    if (!o.net || !o.net.sizes) throw new Error(`${p}: file has no .net — is it a brain file?`);
    return o;
}

module.exports = { loadBrainFile };
