/* bake_brain.js — turn a trained champion into the default_brain.js the page loads.
 *
 *   node bake_brain.js                          training/champion.json -> default_brain.js
 *   node bake_brain.js training/run2_champ.json
 *
 * Refuses to bake a brain whose corpus hash or embedding width does not match
 * the current task bank. A brain evolved against different sentences still
 * *runs* — the vectors are the same shape — it just quietly means something
 * else by every input, and that is the kind of mismatch that costs an evening.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { loadSim } = require("./simload.js");
loadSim(__dirname);

const src = process.argv[2] || path.join("training", "champion.json");
const p = path.isAbsolute(src) ? src : path.join(__dirname, src);
if (!fs.existsSync(p)) {
    console.error(`no champion at ${src}. Train one first:  node train.js --gens 400`);
    process.exit(1);
}
const saved = JSON.parse(fs.readFileSync(p, "utf8"));

const want = corpusHash();
if (saved.corpusHash && saved.corpusHash !== want) {
    console.error(`corpus mismatch: brain was evolved against ${saved.corpusHash}, the bank is now ${want}.`);
    console.error(`Either re-train, or check out the tasks.js the brain was trained on.`);
    process.exit(1);
}
if (saved.embDim && saved.embDim !== Embedding.dim) {
    console.error(`embedding width mismatch: brain expects ${saved.embDim}, task_embeddings.js provides ${Embedding.dim}.`);
    process.exit(1);
}
if (saved.embModel && Embedding.meta && saved.embModel !== Embedding.meta.model) {
    console.error(`embedder mismatch: brain was evolved on ${saved.embModel}, the bake is ${Embedding.meta.model}.`);
    process.exit(1);
}

// sanity: the brain must actually load and produce finite output
const brain = Brain.fromJSON(saved.brain);
const out = brain.act(new Float32Array(MOTOR_FEATS).fill(0.1));
for (let i = 0; i < 5; i++) if (!Number.isFinite(out[i])) {
    console.error("champion produces non-finite output — refusing to bake");
    process.exit(1);
}

const payload = {
    gen: saved.gen, fitness: saved.fitness, championGen: saved.championGen,
    stage: saved.stage, embDim: saved.embDim, embModel: saved.embModel,
    corpusHash: saved.corpusHash, brain: saved.brain
};
const outPath = path.join(__dirname, "default_brain.js");
fs.writeFileSync(outPath,
    `/* default_brain.js — GENERATED by bake_brain.js from ${path.basename(src)}. Do not edit.\n` +
    ` * gen ${saved.gen}, fitness ${Math.round(saved.fitness || 0)}, embedder ${saved.embModel}, corpus ${saved.corpusHash}\n` +
    ` */\n"use strict";\nconst DEFAULT_BRAIN = ${JSON.stringify(payload)};\n` +
    `if (typeof module !== "undefined") module.exports = { DEFAULT_BRAIN };\n`);

console.log(`baked default_brain.js — gen ${saved.gen}, fitness ${Math.round(saved.fitness || 0)}, ` +
    `${(fs.statSync(outPath).size / 1024).toFixed(0)} kB`);
