/* make_scaffold.js — bake the searched rise trajectories into the trainer.
 *
 *   node make_scaffold.js [--min 0.70]
 *
 * Reads rise_ref_<pose>.json (written by probe_rise_search.js) and emits ONE
 * source of truth in two forms: rise_scaffold.js for the browser and the JS
 * oracle, rise_scaffold.hpp for the C++ trainer. Generating both from the same
 * pass is the point — a scaffold that differs between the two builds would make
 * every episode comparison meaningless, and the difference would be invisible.
 *
 * EVERY REFERENCE IS RE-SIMULATED BEFORE IT IS BAKED, and this is not a
 * formality. A stale rise_ref_kneel.json from a 20-generation smoke test scored
 * 0.602 m and sat on disk looking exactly like the real 500-generation result at
 * 0.716 m — same filename, same shape, same fields. Trusting the file would have
 * quietly baked the weaker trajectory into the run and the only symptom would
 * have been a curriculum that helped less than expected. So the score is
 * measured here, printed, and checked against --min.
 */
"use strict";
const fs = require("fs"), path = require("path"), vm = require("vm");
for (const f of ["nn.js", "physics.js", "body.js", "terrain.js", "walker.js", "rise_scaffold.js", "world.js", "evolution.js"])
    vm.runInThisContext(fs.readFileSync(path.join(__dirname, f), "utf8"), { filename: f });
const M = HUMANOID;

const MIN = (() => { const i = process.argv.indexOf("--min"); return i > 0 ? +process.argv[i + 1] : 0.65; })();
const POSES = ["kneel", "quadruped", "prone"];
const T_RISE = 3.0, SETTLE = 0.5;
const STEPS = Math.round(T_RISE / DT), SETTLE_STEPS = Math.round(SETTLE / DT);
const inert = { sizes: NET_SIZES.slice(), forward: () => new Float32Array(NOUT).fill(0.5) };

function poseByName(name) {
    if (name === "prone" || name === "supine")
        return (M.groundPoses || []).find(p => p.name === name) || M.groundPoses[0];
    return M.startPoses.find(p => p.name === name) || (M.groundPoses || []).find(p => p.name === name);
}

/* Replay exactly as probe_rise_search.js scored it — same episode length, same
 * settle window, same output-space mapping — or the number printed here is not
 * the number the search reported. */
function replay(gene, knots, pose) {
    const w = new World(M, [inert], {
        stage: 1, terrainDifficulty: 0, terrainId: "flat", missionSeed: 31,
        noiseSeed: 17, noise: false, startPose: pose, groundFrac: 1, seatFrac: 0, poseFrac: 1
    });
    const k = w.walkers[0];
    let acc = 0, n = 0, start = 0, peak = 0;
    for (let step = 0; step < STEPS; step++) {
        w.step();
        const u = step / (STEPS - 1) * (knots - 1);
        const i0 = Math.min(knots - 2, Math.floor(u)), f = u - i0;
        for (let j = 0; j < M.nj; j++) {
            const a = gene[j * knots + i0], b = gene[j * knots + i0 + 1];
            const out = a + (b - a) * f;
            const bd = M.bodies[j + 1];
            let c = M.nominal[j] + (out * 2 - 1) * M.range[j];
            k.cmd[j] = c < bd.qmin ? bd.qmin : c > bd.qmax ? bd.qmax : c;
        }
        const com = k.comHeight(w);
        if (!start) start = com;
        if (com > peak) peak = com;
        if (step >= STEPS - SETTLE_STEPS) { acc += com; n++; }
    }
    return { start, peak, settled: acc / n };
}

const baked = {};
let worst = Infinity;
console.log(`re-simulating each reference before baking (min accepted ${MIN.toFixed(2)} m)\n`);
console.log("  pose         start     peak      settled   claimed   agrees");
for (const name of POSES) {
    const p = path.join(__dirname, `rise_ref_${name}.json`);
    if (!fs.existsSync(p)) { console.log(`  ${name.padEnd(12)} MISSING — run probe_rise_search.js ${name}`); continue; }
    const ref = JSON.parse(fs.readFileSync(p, "utf8"));
    const pose = poseByName(name);
    const r = replay(ref.gene, ref.knots, pose);
    /* The claimed score travels in the file. If the replay disagrees the file was
     * written by a different physics or a different scoring rule, and baking it
     * would silently change what the curriculum teaches. */
    const agrees = Math.abs(r.settled - ref.score) < 0.005;
    console.log(`  ${name.padEnd(12)} ${r.start.toFixed(3)} m   ${r.peak.toFixed(3)} m   ` +
        `${r.settled.toFixed(3)} m   ${ref.score.toFixed(3)} m   ${agrees ? "yes" : "NO — REJECTED"}`);
    if (!agrees) continue;
    if (r.settled < MIN) { console.log(`               below --min, not baked`); continue; }
    worst = Math.min(worst, r.settled);
    baked[name] = { knots: ref.knots, T: ref.T, gene: ref.gene, settled: r.settled, start: r.start };
}

const names = Object.keys(baked);
if (!names.length) { console.error("\nnothing passed — refusing to write an empty scaffold"); process.exit(1); }

const stamp = new Date().toISOString().slice(0, 19) + "Z";
const head = `/* GENERATED by make_scaffold.js — do not edit by hand.
 *
 * Searched open-loop rise trajectories, in NETWORK OUTPUT SPACE, one per contact
 * rung. Each drives the joints for the first part of a scaffolded rise episode
 * and then hands over to the brain mid-motion; see the scaffolding note in
 * walker.js control() for why handover beats spawning at a mid-rise posture.
 *
 * Baked ${stamp}. Each was re-simulated at bake time:
${names.map(n => ` *   ${n.padEnd(11)} ${baked[n].start.toFixed(3)} m -> ${baked[n].settled.toFixed(3)} m settled`).join("\n")}
 * A walker commanded to hold the nominal standing posture settles at 0.955 m,
 * which is the ceiling these should be read against. */`;

fs.writeFileSync(path.join(__dirname, "rise_scaffold.js"),
    head + "\nvar RISE_SCAFFOLD = " + JSON.stringify(baked, (k, v) =>
        typeof v === "number" ? +v.toFixed(6) : v) + ";\n" +
    'if (typeof module !== "undefined") module.exports = { RISE_SCAFFOLD };\n');

let hpp = head.replace(/^\/\* GENERATED/, "/* GENERATED") + "\n#pragma once\n#include <vector>\n#include <string>\n\n" +
    "struct RiseRef { const char* name; int knots; double T; std::vector<double> gene; };\n" +
    "static const std::vector<RiseRef> RISE_SCAFFOLD = {\n";
for (const n of names) {
    const b = baked[n];
    hpp += `    { "${n}", ${b.knots}, ${b.T}, {` +
        Array.from(b.gene).map(v => v.toFixed(6)).join(", ") + "} },\n";
}
hpp += "};\n";
fs.writeFileSync(path.join(__dirname, "rise_scaffold.hpp"), hpp);

console.log(`\nbaked ${names.length} reference(s): ${names.join(", ")}`);
console.log(`wrote rise_scaffold.js and rise_scaffold.hpp — weakest baked rise settles at ${worst.toFixed(3)} m`);
