/* progress.js — what the run looks like, rather than what it prints.
 *
 *   node progress.js --champion training/champion.json --log training/run.log
 *   node progress.js --watch training            (re-renders as the run advances)
 *
 * Writes into progress/ :
 *   curves.svg              every metric in the log, one panel each
 *   gen0123_walk.svg        filmstrip of the champion crossing ground
 *   gen0123_rise.svg        filmstrip of it getting off the floor
 *   index.html              all of it on one page, newest first
 *
 * Everything is SVG generated by hand. No canvas, no headless browser, no
 * dependencies — the whole point is that this keeps working on a machine with
 * nothing installed, and vector frames stay readable when you zoom into a foot
 * to see whether the toe actually cleared.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const DIR = __dirname;
const OUT = path.join(DIR, "progress");

function arg(name, dflt) {
    const i = process.argv.indexOf("--" + name);
    if (i < 0) return dflt;
    const v = process.argv[i + 1];
    if (v === undefined || v.startsWith("--")) return true;
    return isNaN(+v) ? v : +v;
}

function loadSim() {
    for (const f of ["nn.js", "physics.js", "body.js", "terrain.js", "walker.js", "rise_scaffold.js", "world.js", "evolution.js"]) {
        vm.runInThisContext(fs.readFileSync(path.join(DIR, f), "utf8"), { filename: f });
    }
}

/* ------------------------------------------------------------------ 3D → SVG
 * A painter's-algorithm renderer for boxes, which is all this body is made of.
 * Faces are sorted back to front and shaded by how square-on they face the
 * light; there is no z-buffer because with two dozen convex boxes and no
 * interpenetration (which the body no longer has) sorting by depth is exact
 * enough to look right. */
/* The camera frames the walker's centre of mass, not a fixed height. A fixed
 * look-at works for a standing figure and pushes a prone one off the bottom of
 * the frame — which is exactly the half of the run worth watching now. */
const CAM = { dist: 3.0, yaw: 0.62, fov: 1.0 };

function makeCamera(target) {
    const aim = Math.max(0.42, Math.min(1.0, target[1]));
    const cy = Math.cos(CAM.yaw), sy = Math.sin(CAM.yaw);
    const eye = [target[0] + CAM.dist * cy, aim + 0.35, target[2] + CAM.dist * sy];
    const f = [target[0] - eye[0], aim - eye[1], target[2] - eye[2]];
    const fl = Math.hypot(f[0], f[1], f[2]);
    f[0] /= fl; f[1] /= fl; f[2] /= fl;
    // right = normalise(f x up), up = right x f
    let r = [f[2] * 0 - f[1] * 0, 0, 0];
    r = [f[2], 0, -f[0]];
    const rl = Math.hypot(r[0], r[2]); r[0] /= rl; r[2] /= rl;
    const u = [r[2] * f[1] - 0 * f[2], 0 * f[0] - r[0] * f[1], r[0] * f[2] - r[2] * f[0]];
    return { eye, f, r, u };
}
function project(cam, p, w, h) {
    const d = [p[0] - cam.eye[0], p[1] - cam.eye[1], p[2] - cam.eye[2]];
    const z = d[0] * cam.f[0] + d[1] * cam.f[1] + d[2] * cam.f[2];
    if (z <= 0.05) return null;
    const x = d[0] * cam.r[0] + d[1] * cam.r[1] + d[2] * cam.r[2];
    const y = d[0] * cam.u[0] + d[1] * cam.u[1] + d[2] * cam.u[2];
    const s = (h * 0.5) / (Math.tan(CAM.fov * 0.5) * z);
    return [w * 0.5 + x * s, h * 0.5 - y * s, z];
}

const BOX_FACES = [
    [0, 1, 3, 2], [4, 6, 7, 5], [0, 4, 5, 1],
    [2, 3, 7, 6], [0, 2, 6, 4], [1, 5, 7, 3]
];
const LIGHT = (() => { const v = [0.42, 0.82, 0.38]; const l = Math.hypot(...v); return v.map(x => x / l); })();

/* One frame: every box of the walker, plus a ground grid, as SVG. */
function frame(M, mb, cam, w, h, hue) {
    const quads = [];
    const P = new Float64Array(3);
    for (let i = 0; i < M.bodies.length; i++) {
        for (const b of M.bodies[i].boxes) {
            const hx = b.d[0] / 2, hy = b.d[1] / 2, hz = b.d[2] / 2;
            const corners = [];
            for (let k = 0; k < 8; k++) {
                mb.worldPoint(i,
                    b.c[0] + (k & 1 ? hx : -hx),
                    b.c[1] + (k & 2 ? hy : -hy),
                    b.c[2] + (k & 4 ? hz : -hz), P, 0);
                corners.push([P[0], P[1], P[2]]);
            }
            for (const f of BOX_FACES) {
                const pts = f.map(k => project(cam, corners[k], w, h));
                if (pts.some(p => !p)) continue;
                const a = corners[f[0]], b2 = corners[f[1]], c = corners[f[2]];
                const e1 = [b2[0] - a[0], b2[1] - a[1], b2[2] - a[2]];
                const e2 = [c[0] - a[0], c[1] - a[1], c[2] - a[2]];
                let n = [e1[1] * e2[2] - e1[2] * e2[1], e1[2] * e2[0] - e1[0] * e2[2], e1[0] * e2[1] - e1[1] * e2[0]];
                const nl = Math.hypot(...n) || 1; n = n.map(x => x / nl);
                const toCam = [cam.eye[0] - a[0], cam.eye[1] - a[1], cam.eye[2] - a[2]];
                if (n[0] * toCam[0] + n[1] * toCam[1] + n[2] * toCam[2] < 0) continue;   // backface
                const lam = Math.max(0, n[0] * LIGHT[0] + n[1] * LIGHT[1] + n[2] * LIGHT[2]);
                const lum = 34 + 46 * lam;
                const depth = (pts[0][2] + pts[1][2] + pts[2][2] + pts[3][2]) / 4;
                quads.push({ depth, d: pts.map(p => `${p[0].toFixed(1)},${p[1].toFixed(1)}`).join(" "), lum });
            }
        }
    }
    quads.sort((a, b) => b.depth - a.depth);
    let s = "";
    let x0 = 1e9, x1 = -1e9, y0 = 1e9, y1 = -1e9;
    for (const q of quads) {
        s += `<polygon points="${q.d}" fill="hsl(${hue} 46% ${q.lum.toFixed(0)}%)" stroke="hsl(${hue} 40% 18%)" stroke-width="0.5"/>`;
        for (const pt of q.d.split(" ")) {
            const c = pt.split(","); const a = +c[0], b = +c[1];
            if (a < x0) x0 = a; if (a > x1) x1 = a; if (b < y0) y0 = b; if (b > y1) y1 = b;
        }
    }
    return { svg: s, bbox: quads.length ? [x0, y0, x1, y1] : null };
}

/* Fit whatever the frame contains into the frame. A single camera cannot hold
 * both a standing figure and one lying flat 20 cm off the ground without one of
 * them leaving the picture, and both are worth seeing. */
function fitTransform(bbox, w, h, pad) {
    if (!bbox) return "";
    const bw = Math.max(1e-3, bbox[2] - bbox[0]), bh = Math.max(1e-3, bbox[3] - bbox[1]);
    const k = Math.min((w - 2 * pad) / bw, (h - 2 * pad) / bh, 1.9);
    const cx = (bbox[0] + bbox[2]) / 2, cy = (bbox[1] + bbox[3]) / 2;
    return `translate(${(w / 2 - cx * k).toFixed(2)},${(h / 2 - cy * k).toFixed(2)}) scale(${k.toFixed(4)})`;
}

function groundGrid(cam, w, h, cx, cz) {
    let s = "";
    const step = 0.5, span = 5;
    const line = (x1, z1, x2, z2, op) => {
        const a = project(cam, [x1, 0, z1], w, h), b = project(cam, [x2, 0, z2], w, h);
        if (!a || !b) return;
        s += `<line x1="${a[0].toFixed(1)}" y1="${a[1].toFixed(1)}" x2="${b[0].toFixed(1)}" y2="${b[1].toFixed(1)}" stroke="#5a6570" stroke-width="0.6" opacity="${op}"/>`;
    };
    const x0 = Math.round(cx / step) * step, z0 = Math.round(cz / step) * step;
    for (let i = -span; i <= span; i++) {
        line(x0 + i * step, z0 - span * step, x0 + i * step, z0 + span * step, 0.30);
        line(x0 - span * step, z0 + i * step, x0 + span * step, z0 + i * step, 0.30);
    }
    return s;
}

/* Run one episode and grab N frames, evenly spaced over the part that matters. */
function filmstrip(net, opts) {
    const M = HUMANOID;
    const world = new World(M, [net], opts.world);
    const x = world.walkers[0];
    if (opts.pose) { x.reset(world, world.spawn.x, world.spawn.z, world.startYaw, opts.pose); x.timeLeft = opts.budget || 22; }
    const FR = opts.frames || 6;
    const shots = [];
    const maxT = opts.seconds || 14;
    // Sample densely and subsample at the end, rather than spacing frames over
    // the episode length we HOPE for. An episode that ends at four seconds
    // otherwise yields two frames and a mostly empty strip, and early in a run
    // that is most of them.
    const every = Math.max(1, Math.floor(0.25 * 500));
    let t = 0;
    const W = 210, H = 260;
    while (!world.isOver() && t < maxT * 500) {
        world.step(); t++;
        if (t % every === 0) {
            const cam = makeCamera([x.mb.bp[0], x.comHeight(world), x.mb.bp[2]]);
            const body = frame(M, x.mb, cam, W, H, opts.hue || 150);
            const fit = fitTransform(body.bbox, W, H, 26);
            shots.push({
                svg: `<g transform="${fit}">` + groundGrid(cam, W, H, x.mb.bp[0], x.mb.bp[2]) + body.svg + `</g>`,
                t: (t / 500).toFixed(1),
                com: x.comHeight(world).toFixed(2),
                up: x.uprightness().toFixed(2),
                down: x.downed
            });
        }
    }
    let picked = shots;
    if (shots.length > FR) {
        picked = [];
        for (let i = 0; i < FR; i++) picked.push(shots[Math.round(i * (shots.length - 1) / (FR - 1))]);
    }
    return { shots: picked, walker: x, world, W, H };
}

function stripSVG(title, sub, strip) {
    const { shots, W, H } = strip;
    const w = shots.length * W, h = H + 46;
    let s = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" font-family="ui-monospace,Menlo,Consolas,monospace">`;
    s += `<rect width="${w}" height="${h}" fill="#11161c"/>`;
    s += `<text x="10" y="20" fill="#d8e0e8" font-size="13">${title}</text>`;
    s += `<text x="10" y="36" fill="#7f8b98" font-size="11">${sub}</text>`;
    shots.forEach((sh, i) => {
        s += `<g transform="translate(${i * W},46)">`;
        s += `<rect width="${W - 2}" height="${H}" fill="#161c24" stroke="#232c36"/>`;
        s += sh.svg;
        s += `<text x="6" y="14" fill="${sh.down ? "#e0956b" : "#6fbf8f"}" font-size="10">${sh.t}s  com ${sh.com}m  up ${sh.up}</text>`;
        s += `</g>`;
    });
    return s + "</svg>";
}

/* ------------------------------------------------------------------- curves */
/* Prefer runlog.json — the trainer writes it unconditionally, whereas run.log
 * only exists if somebody redirected stdout, and parsing numbers back out of a
 * line of formatted text is a way to silently mis-read them. The text parser
 * stays as a fallback for the runs that only left a log behind. */
function parseLog(file) {
    const asJson = path.join(path.dirname(file), "runlog.json");
    if (fs.existsSync(asJson)) {
        try {
            const j = JSON.parse(fs.readFileSync(asJson, "utf8"));
            if (Array.isArray(j) && j.length) return j.map((r, i) => ({
                gen: i + 1, stage: r.stage || 1, best: r.best || 0, avg: r.avg || 0,
                stood: (r.stoodFrac || 0) * 100, bal: (r.balancedFrac || 0) * 100,
                steps: r.avgSteps || 0, walked: r.avgProg || 0, bestWalked: r.bestProg || 0,
                rose: (r.roseFrac || 0) * 100, wp: r.avgArr || 0, bestWp: r.bestArr || 0
            }));
        } catch (e) { /* fall through to the text log */ }
    }
    if (!fs.existsSync(file)) return [];
    const rows = [];
    for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
        const m = /^gen\s+(\d+)\s+st(\d)\s+best\s+(-?\d+)\s+avg\s+(-?\d+).*?stood\s+(\d+)%\s+bal\s+(\d+)%.*?steps\s+([\d.]+)\/.*?walked\s+([\d.]+)\/([\d.]+)/.exec(line);
        if (!m) continue;
        const rose = /rose\s+(\d+)%/.exec(line);
        const wp = /wp\s+([\d.]+)\/([\d.]+)/.exec(line);
        rows.push({
            gen: +m[1], stage: +m[2], best: +m[3], avg: +m[4], stood: +m[5], bal: +m[6],
            steps: +m[7], walked: +m[8], bestWalked: +m[9],
            rose: rose ? +rose[1] : 0, wp: wp ? +wp[1] : 0, bestWp: wp ? +wp[2] : 0
        });
    }
    return rows;
}

const PANELS = [
    { key: "avg", key2: "best", label: "fitness (mean / best)", fmt: v => v.toFixed(0) },
    { key: "walked", key2: "bestWalked", label: "metres walked (mean / best)", fmt: v => v.toFixed(2) },
    { key: "wp", key2: "bestWp", label: "waypoints reached (mean / best)", fmt: v => v.toFixed(2) },
    { key: "bal", label: "% balanced", fmt: v => v.toFixed(0) },
    { key: "rose", label: "% of floor starts it got up from", fmt: v => v.toFixed(0) },
    { key: "steps", label: "steps per episode", fmt: v => v.toFixed(1) }
];

function curvesSVG(rows) {
    if (!rows.length) return `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="40"><text x="8" y="24" fill="#888" font-family="monospace">no generations logged yet</text></svg>`;
    const PW = 560, PH = 150, PAD = 46, COLS = 2;
    const rowsN = Math.ceil(PANELS.length / COLS);
    const W = COLS * PW, H = rowsN * PH + 34;
    let s = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="ui-monospace,Menlo,Consolas,monospace">`;
    s += `<rect width="${W}" height="${H}" fill="#11161c"/>`;
    s += `<text x="12" y="21" fill="#d8e0e8" font-size="13">training curves — ${rows.length} generations, stage ${rows[rows.length - 1].stage}</text>`;
    const gmax = rows[rows.length - 1].gen || 1;

    PANELS.forEach((p, i) => {
        const ox = (i % COLS) * PW, oy = 34 + Math.floor(i / COLS) * PH;
        const iw = PW - PAD - 14, ih = PH - 44;
        let vmax = 0;
        for (const r of rows) { vmax = Math.max(vmax, r[p.key] || 0, p.key2 ? (r[p.key2] || 0) : 0); }
        if (vmax <= 0) vmax = 1;
        s += `<g transform="translate(${ox},${oy})">`;
        s += `<text x="${PAD}" y="12" fill="#9aa7b4" font-size="11">${p.label}</text>`;
        s += `<rect x="${PAD}" y="18" width="${iw}" height="${ih}" fill="#141a21" stroke="#222a33"/>`;
        for (let g = 0; g <= 4; g++) {
            const y = 18 + ih - (ih * g / 4);
            s += `<line x1="${PAD}" y1="${y.toFixed(1)}" x2="${PAD + iw}" y2="${y.toFixed(1)}" stroke="#1e2630"/>`;
            s += `<text x="${PAD - 5}" y="${(y + 3).toFixed(1)}" fill="#5f6b78" font-size="9" text-anchor="end">${p.fmt(vmax * g / 4)}</text>`;
        }
        const pathFor = (key, colour, wdt, op) => {
            let d = "";
            rows.forEach(r => {
                const v = r[key] || 0;
                const x = PAD + iw * (r.gen / gmax);
                const y = 18 + ih - ih * (v / vmax);
                d += (d ? "L" : "M") + x.toFixed(1) + "," + y.toFixed(1);
            });
            s += `<path d="${d}" fill="none" stroke="${colour}" stroke-width="${wdt}" opacity="${op}"/>`;
        };
        if (p.key2) pathFor(p.key2, "#4f7fb8", 1, 0.65);
        pathFor(p.key, "#6fbf8f", 1.6, 1);
        // stage changes, because a step in every curve at once is the curriculum
        let last = rows[0].stage;
        for (const r of rows) {
            if (r.stage !== last) {
                const x = PAD + iw * (r.gen / gmax);
                s += `<line x1="${x.toFixed(1)}" y1="18" x2="${x.toFixed(1)}" y2="${18 + ih}" stroke="#c98b4b" stroke-dasharray="3 3" opacity="0.7"/>`;
                last = r.stage;
            }
        }
        s += `<text x="${PAD}" y="${18 + ih + 13}" fill="#5f6b78" font-size="9">gen 0</text>`;
        s += `<text x="${PAD + iw}" y="${18 + ih + 13}" fill="#5f6b78" font-size="9" text-anchor="end">gen ${gmax}</text>`;
        s += `</g>`;
    });
    return s + "</svg>";
}

/* -------------------------------------------------------------------- index */
function writeIndex() {
    const files = fs.readdirSync(OUT).filter(f => /^gen\d+_/.test(f)).sort().reverse();
    const seen = new Map();
    for (const f of files) {
        const g = /^gen(\d+)_(\w+)\.svg$/.exec(f);
        if (!g) continue;
        const k = +g[1];
        if (!seen.has(k)) seen.set(k, {});
        seen.get(k)[g[2]] = f;
    }
    let h = `<!doctype html><meta charset="utf-8"><title>walker — evolution log</title>
<style>
body{background:#0d1116;color:#cdd6df;font:14px ui-monospace,Menlo,Consolas,monospace;margin:0;padding:24px}
h1{font-size:17px;font-weight:600;margin:0 0 4px}
h2{font-size:13px;color:#8b98a5;font-weight:500;margin:26px 0 8px;border-top:1px solid #1e262f;padding-top:14px}
img{max-width:100%;display:block;margin:6px 0;border-radius:4px}
.sub{color:#6d7883;font-size:12px;margin-bottom:18px}
</style>
<h1>walker — evolution log</h1>
<div class="sub">generated by progress.js · newest first</div>
<img src="curves.svg" alt="training curves">`;
    for (const [gen, v] of [...seen.entries()].sort((a, b) => b[0] - a[0])) {
        h += `<h2>generation ${gen}</h2>`;
        if (v.walk) h += `<img src="${v.walk}" alt="walking, gen ${gen}">`;
        if (v.rise) h += `<img src="${v.rise}" alt="rising, gen ${gen}">`;
    }
    fs.writeFileSync(path.join(OUT, "index.html"), h);
}

/* --------------------------------------------------------------------- main */
function renderChampion(file, logFile) {
    const saved = JSON.parse(fs.readFileSync(file, "utf8"));
    const net = Net.fromJSON(saved.net);
    if (net.sizes.join() !== NET_SIZES.join()) {
        console.log(`  skipped: champion is ${net.sizes.join("-")}, this build needs ${NET_SIZES.join("-")}`);
        return null;
    }
    const gen = saved.gen || 0;
    const tag = "gen" + String(gen).padStart(4, "0");

    const walk = filmstrip(net, {
        world: { stage: 3, missionSeed: 1 + 913 * 37, noiseSeed: 5000 + 913 * 13, noise: true, groundFrac: 0 },
        frames: 7, seconds: 16, hue: 150
    });
    const wx = walk.walker;
    fs.writeFileSync(path.join(OUT, `${tag}_walk.svg`), stripSVG(
        `generation ${gen} — walking`,
        `fitness ${(saved.fitness || 0).toFixed(0)} · walked ${wx.progressM.toFixed(2)} m · ${wx.steps} steps · ${wx.arrivals} waypoint(s) · upright ${wx.uprightTime.toFixed(1)}s`,
        walk));

    const pose = HUMANOID.groundPoses[3] || HUMANOID.groundPoses[0];   // supine if present
    const rise = filmstrip(net, {
        world: { stage: 3, missionSeed: 1 + 971 * 37, noiseSeed: 5000 + 971 * 13, noise: true, groundFrac: 0 },
        pose, frames: 7, seconds: 16, budget: 22, hue: 28
    });
    const rx = rise.walker;
    fs.writeFileSync(path.join(OUT, `${tag}_rise.svg`), stripSVG(
        `generation ${gen} — starting ${pose.name}`,
        `peak centre of mass ${rx.bestComY.toFixed(2)} m · recoveries ${rx.recoveries} · ${rx.downed ? "still down at the end" : "back on its feet"}`,
        rise));

    if (logFile) fs.writeFileSync(path.join(OUT, "curves.svg"), curvesSVG(parseLog(logFile)));
    writeIndex();
    return gen;
}

(function main() {
    fs.mkdirSync(OUT, { recursive: true });
    loadSim();
    const watchDir = arg("watch", null);
    if (watchDir) {
        const champ = path.join(DIR, watchDir, "champion.json");
        const log = path.join(DIR, watchDir, "run.log");
        let last = -1;
        const tick = () => {
            try {
                if (fs.existsSync(champ)) {
                    const g = JSON.parse(fs.readFileSync(champ, "utf8")).gen;
                    if (g !== last) { last = g; const done = renderChampion(champ, log); if (done !== null) console.log(`[progress] rendered generation ${done}`); }
                    else if (fs.existsSync(log)) { fs.writeFileSync(path.join(OUT, "curves.svg"), curvesSVG(parseLog(log))); }
                }
            } catch (e) { /* mid-write; try again next tick */ }
        };
        tick();
        setInterval(tick, 30000);
        console.log(`[progress] watching ${watchDir} -> progress/`);
        return;
    }
    const champ = arg("champion", "training/champion.json");
    const log = arg("log", "training/run.log");
    const g = renderChampion(path.isAbsolute(champ) ? champ : path.join(DIR, champ),
        path.isAbsolute(log) ? log : path.join(DIR, log));
    console.log(g === null ? "nothing rendered" : `wrote progress/ for generation ${g}`);
})();
